- build.gradle
- settings.gradle
- src/main/java/online/partyrun/partyrunmatchingservice/PartyRunMatchingServiceApplication.java
- src/test/java/online/partyrun/partyrunmatchingservice/PartyRunMatchingServiceApplicationTests.java
- gradle root 디렉터리 변경
- jacoco 설정 변경
- client docs 추가
기존 템플릿 설정대로 했을 때 root package 설정이 안돼서 build 가 안될 뿐더러
jacoco 실행조차 안되는 문제가 발생했습니다.
webflux 환경에 맞게 초기 설정이 필요합니다.
build가 성공적으로 수행되도록 진행했습니다
> feat : gradle-spring project를 초기 설정 PAR-181

- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/dto/WaitingEvent.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/dto/WaitingStatus.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingService.java
- src/main/java/online/partyrun/partyrunmatchingservice/global/sse/MultiSinkHandler.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingControllerTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingServiceTest.java
Waiting 관련 Server Sent Event 구독하는 로직을 구현했습니다.
기존 WaitingEvent에서 WaitingStatus로 클래스명을 변경한 후 Status를 추가했습니다.
구현내용 관련 단위 테스트 추가했습니다
> feat : waiting 관련 SSE 구독 로직 구현

- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
@BeforeEach 를 통해 register가 이미 실행되고 있으므로
중복/불필요한 테스트 환경설정 코드를 삭제합니다.
> Refactor: 불필요한 코드 삭제

- src/docs/asciidoc/index.adoc
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingController.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingRequest.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/Matching.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMember.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMemberStatus.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingStatus.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepository.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepositoryTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
Matching에 대한 수락/거절을 요청하는 controller 구현
Matchiing에 수락 거절요청을 받고 맴버 상태를 변경 후 각 맴버 상태를 이벤트로 전송하게끔 구현
현재는 기존에 규정했던 API 문서에 맞게 작성을 했으나, matching 수락/거절이 POST matching이 맞을 지 좀 더 논의가 필요할 듯 합니다. 해당 행위가 matching을 생성하는 것이 아닌 매칭에 대한 수락/거절 정보를 전송하는 것인데. 해당 요청이 restful한 지 논의가 필요할 듯 합니다.
> feat : 클라이언트가 matching에 대한 수락/거절 요청 전송 구현 #PAR-193

- src/docs/asciidoc/index.adoc
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingController.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
matching에 관한 이벤트를 구독하고, event stream 응답 로직을 구현했습니다.
event가 wait이 아닌 status가 되면 complete되도록 구현하였습니다.
기존 waitingController-waitingEventService와 구조가 유사합니다.
> feat : matching event 구독 및 이벤트 스트림 응답 로직 구현

- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepository.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
기존에 matching service 로직 중 메서드 부분이 너무 길이가 길어 가독성이 떨어지는 문제가 있었습니다. 메서드 추출을 통해 한 메서드 길이를 단축하여 한 메서드가 한 기능을 위주로 가지게 하여 가독성 및 재사용성을 높이기위해 다음과 같이 리펙터링 진행했습니다.
> refactor : matchingService 로직 메서드 추출 리펙터링

- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueue.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/WaitingQueue.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingMessageListener.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueueTest.java
- waitingQueue 에서 statisfyCount -> isSatisfyCount로 변경하였습니다.
- matchingService 부분에 flatmap에 혼용하는 일부 로직 doOnNext로 분리하였습니다.
-  가독성을 위해 Function 리턴 보다는 Reactor 형 리턴으로 통일하였습니다. 
- matchingService create 로직을 한 파이프라인으로 돌도록 변경하였습니다.
> refactor : waitingQueue, matchingSerivce 부분 리펙터링

- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/Matching.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepository.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/InMemoryWaitingQueue.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/queue/WaitingQueue.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingMessageListener.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingService.java
- src/main/java/online/partyrun/partyrunmatchingservice/global/config/ScheduleConfig.java
- src/main/java/online/partyrun/partyrunmatchingservice/global/config/TimeConfig.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepositoryTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
- Matching 에 Timeout 판단 추가
- MatchingRepository에 Status별 findAll 추가
- MatchingService에 주기적으로 스케줄러를 동작하여 잔여 Sink를 삭제
- WaitingQueue에서 해당 맴버 포함 여부를 확인 가능
- Schedule 및 Clock Config 추가
- MatchingService 스케줄러가 비동기로 동작하여 테스트 코드 내 Delay를 설정하였습니다.
- WaitingService와 WaitingEventService의 관심사가 비슷하여 추후 두 서비스 병합을 고려하는 부분도 논의가 필요해보입니다.
> feat : matching/waiting에서 무응답한 SSE Sink 주기적으로 삭제 #PAR-189

- src/docs/asciidoc/index.adoc
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/Matching.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMember.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/InvalidDistanceException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/InvalidIdException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/InvalidMatchingIdException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/InvalidMembersException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/exception/NotExistMembersException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/exception/DuplicateMemberException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/exception/InvalidDistanceException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/exception/NotAllowDistanceException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/exception/NotSatisfyCountException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/root/RunningDistance.java
- src/main/java/online/partyrun/partyrunmatchingservice/global/controller/HttpControllerAdvice.java
- src/main/java/online/partyrun/partyrunmatchingservice/global/exception/BadRequestException.java
- src/main/java/online/partyrun/partyrunmatchingservice/global/exception/InternalServerException.java
- src/main/java/online/partyrun/partyrunmatchingservice/global/exception/InvalidSinksKeyException.java
- src/main/java/online/partyrun/partyrunmatchingservice/global/exception/SseConnectionException.java
- src/test/java/online/partyrun/partyrunmatchingservice/config/docs/WebfluxDocsTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingMemberTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/MatchingTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingControllerTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/root/RunningDistanceTest.java
- InvalidDistanceException, NotAllowDistanceException 통합
- Http status 별 abstract controller 구현
- 각 예외 클래스를 http Status 별 클래스를 상속받음
- Controller Advice 추가 
기존에는 예외 발생 시 클라이언트에게 별도 메시지를 전달하는 부분이 없었습니다. 또한, 에러 로그를 그대로 전송하여 보안에 치명적인 문제를 제공하였습니다. 해당 부분을 보완하기 위해 Controller Advice를 적용하고, 각 Exception을 Http status 수준으로 추상/구체화를 진행했습니다.
> feat : controller advice 설정 

- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingController.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/dto/WaitingEventResponse.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
waiting event format을 클라이언트 요구에 따라 변경했습니다.
ex) "CONNECTED" -> {"status" : "CONNECTED"}
> fix : change waiting-event response format

- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingProcessTest.java
클라이언트의 요구사항에 따라, connection 시도 시에 connect 이벤트를 발행하지 않고, event 구독 시 항상 connected 이벤트가 먼저 전송되도록 변경하였습니다.
> fix : event 구독 시 항상 connected 이벤트가 먼저 전송되도록 변경 

- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingController.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/entity/Matching.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepository.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepositoryTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
matching status 필드를 굳이 가지고 있을 필요가 없어 제거를 하였고, matching member의 status에 따라 matching status를 얻을 수 있도록 설계했습니다.
또한 matching confirm 및 multicast 하는 로직을 publishOn을 통해 별도 스레드에서 동작하게 설정하였습니다.
matching confirm 로직을 별도 스레드에서 동작하는 이유는 향후 battle 생성 로직이 blocking하게 동작하여 블로킹 로직을 별도 스레드에서 진행하게 할 수 있도록 다음과 같이 설정했습니다. 기존 동작로직과 향후 동작 로직에 관한 다이어그램을 아래 첨부합니다.
향후 confirm matching 부분에 battle 생성 요청 로직을 추가할 계획입니다.
webflux 스케줄러 및 publishOn 관련 설명 https://why-doing.tistory.com/135
> refactor : matching status 삭제 및 matching confirm 부분 스레드 분할

- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingController.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/controller/MatchingControllerTest.java
기존 경로가 Restful하지 않아서 URL을 /matching 에서 /matching/members/join 으로 변경했습니다
> refactor : 매칭 참여 여부 API 엔드포인트 변경

- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
기존에 member의 수락/거절 여부를 병렬처리를 통해 업데이트를 진행하여 동시성 문제가 발생했습니다. 
해당 문제를 해결하기 위해 member 수락/거절 업데이트 후 matching 상태에 따른 배틀 생성 요청 및 이벤트 멀티 캐스팅을 싱글 스레드에서 동작하도록 변경하였습니다. 
synchronized, redis 분산락, 트랜젝션 등 다양한 방법을 시도했으나, 결국 멀티 스레드 환경에서는 제약이 많았습니다.
> fix : matching 상태 update 로직 싱글 스레드에서 동작하도록 변경

- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepository.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingService.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/repository/MatchingRepositoryTest.java
최근 매칭 탐색에 대한 repository 로직을 변경했습니다.
기존에는 member id가 포함되는 매칭에서 member가 무응답한 매칭만 전송을 하였습니다. 그러다보니, 이미 ready 여부를 보낸 이후에는 매칭을 조회할 수 없었습니다.
따라서 요구 그대로 필터 없이 최근 매칭에 대한 정보를 전송하도록 변경하였습니다.
> fix : 최근 매칭 탐색 repository 로직 변경

- src/docs/asciidoc/index.adoc
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingController.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingControllerTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
기존에 구현한 cancel을 통해서는 클라이언트 측에서 강제로 disconnect 해도 동작하지 않는 것을 확인했습니다. 로컬에서도 doFinally 등으로도 체이닝 했을 때도 disconnect를 체킹할 방법이 없어서 결국 cancel 로직을 API로 별도로 개발했습니다.
> feat : waiting event 취소 API 구현

- build.gradle
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingSinkHandler.java
- src/main/java/online/partyrun/partyrunmatchingservice/global/advisor/LogAdvisor.java
- src/main/java/online/partyrun/partyrunmatchingservice/global/sse/SinkHandlerTemplate.java
- src/main/resources/application.yml
- src/main/resources/logback-spring.xml
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
기존에 로그를 이용해서 각 컴포넌트를 Trace하는데 어려움이 있어서 AOP를 통해 별도 log를 추적하는 컴포넌트를 구성하였습니다.
log level을 Trace가 아닌 Debug로 한 이유는 Trace시 불필요한 로그 내용이 많았기에 Debug 레벨로 진행하였습니다.
```
[2023-08-17 13:47:10:372][main] TRACE o.s.c.a.ClassPathBeanDefinitionScanner - Ignored because not matching any filter: file [/Users/parkhyeonjun/dev/swm/kms/party-run-matching-service/out/production/classes/online/partyrun/partyrunmatchingservice/global/exception/InternalServerException.class]
[2023-08-17 13:47:10:372][main] TRACE o.s.c.a.ClassPathBeanDefinitionScanner - Scanning file [/Users/parkhyeonjun/dev/swm/kms/party-run-matching-service/out/production/classes/online/partyrun/partyrunmatchingservice/global/exception/InvalidSinksKeyException.class]
[2023-08-17 13:47:10:373][main] TRACE o.s.c.a.ClassPathBeanDefinitionScanner - …
```
> feat : 전역 Debug log 설정 

- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingController.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/controller/WaitingControllerTest.java
waiting event cancel 시에 Http Response status를 204 no content 에서 200 ok로 변경했습니다.
클라이언트 측에서 body가 없으면 error로 간주하는 문제가 발생하였는데, 204 상태일때는 body에 어떠한 값을 넣어도 들어가지 않는 것을 확인하여 200으로 상태를 변경하였습니다.
> refactor : waiting cancel 시 status 변경

- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/dto/WaitingStatus.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventService.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/waiting/service/WaitingEventServiceTest.java
waiting cancel 시 cancel이라는 Event를 추가하여 전달하도록 구현하였습니다.
기존에는 별도 event 없이 complete를 하였는데, 그러다보니 클라이언트 측에서 EOF error가 터지는 문제가 발생했습니다. 
이러한 문제를 해결하기 위해 cancel시에도 event를 전송한 후 complete하도록 변경하였습니다.
> feat : waiting cancel시 Event 추가

- src/docs/asciidoc/index.adoc
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/controller/PartyController.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/dto/PartyEvent.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/dto/PartyIdResponse.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/dto/PartyRequest.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/EntryCode.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/Party.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/PartyStatus.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/repository/PartyRepository.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyService.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartySinkHandler.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/matching/service/MatchingServiceTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/party/controller/PartyControllerTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/party/entity/EntryCodeTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/party/entity/PartyTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyServiceTest.java
같이하기 기능(Party mode에 대한) 기능을 구현하였습니다
3가지 기능을 구현하였습니다.
1.  Party 생성
- Party를 생성하고, 생성자가 방장이 됩니다.
- 참여 코드는 100,000 ~ 999,999 중 무작위 값으로 설정합니다.
- 중복을 대비하여 참여 코드와, Party Id는 별도로 설정했습니다. 
2. Party 참여
- 기존 Waiting, Matching과 달리, event를 구독하면 바로 sink를 생성한 후 구독하도록 설정하였습니다. 
- join시 party에 명단을 추가하고, sink event stream을 전달합니다.
- 다른 참여자들에게도 party에 대한 event를 multicast 합니다. 
3. Party 시작
- party 시작 시에 battle service에 create 요청을 보낸 후 id를 받아와 party에 저장합니다.
- Complete로 상태를 변경한 후, party 참여자들에게 이벤트를 전송하고, sink를 종료시킵니다.
1. PartyEntity에 대한 값 검증
- 현재 null check 및 별도 state에 대한 예외 설정을 해당 PR에 반영을 안했습니다. 다음 PR에 추가할 계획입니다.
6. 방장만 게임 시작 할 수 있도록 설정
7. quit 기능 구현
> feat : 같이하기(party) 관련 API 구현

- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/dto/PartyEvent.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/Party.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/party/controller/PartyControllerTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyServiceTest.java
party leader를 manager로 네이밍을 변경하였습니다.
또한 클라이언트 요구에 따라 event에 distance를 추가하였습니다.
> refactor : party leader -> manager로 네이밍 변경 및 party event에 distance 추가

- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/Party.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/PartyStatus.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyService.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/party/entity/PartyTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyServiceTest.java
파티 나가기 기능을 구현하였습니다. 기존에 Controller을 미리 구축했어서 비즈니스 로직만 추가하면 됐습니다.
만약 방장인 경우 quit 시에 party 자체가 종료되도록 설정하였습니다.
또한, multicast 부분에 중복되는 부분이 있어 리펙터링을 병행하였습니다.
> feat : party 나가기 기능 구현

- src/docs/asciidoc/index.adoc
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/dto/PartyEvent.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/entity/Party.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/exception/IllegalArgumentIdException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/exception/NotSatisfyMemberCountException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/exception/PartyClosedException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/exception/PartyNotFoundException.java
- src/main/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyService.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/party/controller/PartyControllerTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/party/entity/PartyTest.java
- src/test/java/online/partyrun/partyrunmatchingservice/domain/party/service/PartyServiceTest.java
1. 클라이언트 측과의 협의 하에 기존 participants를 ParticipantIds로 이름을 변경했습니다.
2. ParticipantIds Collection을 List에서 Set으로 변경했습니다. 중복을 허용하지 않고, 순서 보장이 필요 없기에 자료구조를 변경했습니다.
3. Party에 대한 Arguments 검증 및 State 검증 로직을 추가하였습니다.
3-1. 전반적인 Arguments에서 String 값이 null 혹은 Blank일 때 검증
3-2. 파티가 이미 모집이 완료됐거나, 캔슬됐을 때 시작 불가
3-3. 파티가 인원수가 충족하지 않으면 시작 불가
4. PartyService에서 사용자가 요청한 Party를 탐색하지 못했을 때의 예외 처리를 추가하였습니다.
> feat : Party Validation 로직 추가
